name: PR Default Setting

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-labeling:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Add Default Label
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            // 라벨이 없을 때만 실행
            if (!pr.data.labels.length) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['D-2']
              });
            }

  auto-assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Update Assignees
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            // assignee가 없을 때만 실행
            if (!pr.data.assignees.length) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: [context.payload.pull_request.user.login]
              });
            }